# Generated by Django 2.1.8 on 2020-03-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensorCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelUUID', models.IntegerField(verbose_name='选中的设备表UUID')),
                ('configUUID', models.IntegerField(verbose_name='选中的配置表UUID')),
                ('numOfCheckedModels', models.IntegerField(default=1, verbose_name='生效的模块数量')),
            ],
            options={
                'verbose_name': '选中的配置',
                'verbose_name_plural': '选中的配置',
            },
        ),
        migrations.CreateModel(
            name='sensorConfig',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('sensorId', models.IntegerField(verbose_name='传感器编号')),
                ('sensorName', models.CharField(max_length=500, verbose_name='传感器名词/位置')),
                ('remark', models.TextField(help_text='详细描述一下该传感器的位置和作用', verbose_name='描述')),
            ],
            options={
                'verbose_name': '传感器位置关系表',
                'verbose_name_plural': '传感器位置关系表',
            },
        ),
        migrations.CreateModel(
            name='sensorConfigName',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('configName', models.CharField(max_length=1000, verbose_name='配置名称')),
                ('remark', models.TextField(help_text='详细描述一下该配置', verbose_name='描述')),
            ],
            options={
                'verbose_name': '传感器配置名称关系对照表',
                'verbose_name_plural': '传感器配置名称关系对照表',
            },
        ),
        migrations.CreateModel(
            name='sensorModelConfig',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('devName', models.CharField(max_length=128, verbose_name='设备路径')),
                ('modelName', models.CharField(max_length=128, verbose_name='设备名称')),
                ('remark', models.TextField(help_text='详细描述一下该设备的作用', verbose_name='描述')),
            ],
            options={
                'verbose_name': '设备路径关系表',
                'verbose_name_plural': '设备路径关系表',
            },
        ),
        migrations.AddField(
            model_name='sensorconfig',
            name='sensorConf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorFront.sensorConfigName', verbose_name='配置'),
        ),
    ]
