# Generated by Django 2.1.8 on 2020-03-25 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorFront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcheckout',
            name='configUUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorFront.sensorConfigName', verbose_name='选中的配置表UUID'),
        ),
        migrations.AlterField(
            model_name='sensorcheckout',
            name='modelUUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorFront.sensorModelConfig', verbose_name='选中的设备表UUID'),
        ),
    ]
