# Generated by Django 2.1.8 on 2020-03-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmcCheckoutConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'BMC选中节点配置表',
                'verbose_name_plural': 'BMC选中节点配置表',
            },
        ),
        migrations.CreateModel(
            name='BmcConfig',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('keyword', models.CharField(max_length=128, verbose_name='关键字')),
                ('description', models.CharField(max_length=128, verbose_name='关键字描述')),
                ('remark', models.CharField(max_length=128, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'BMC配置表',
                'verbose_name_plural': 'BMC配置表',
            },
        ),
        migrations.CreateModel(
            name='BmcConfName',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('confName', models.CharField(max_length=128, verbose_name='配置名称')),
                ('remark', models.TextField(help_text='备注信息', verbose_name='备注')),
            ],
            options={
                'verbose_name': '配置名称表',
                'verbose_name_plural': '配置名称表',
            },
        ),
        migrations.AddField(
            model_name='bmcconfig',
            name='confId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.BmcConfName', verbose_name='配置名称表UUID'),
        ),
        migrations.AddField(
            model_name='bmccheckoutconf',
            name='bmcConfId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.BmcConfName', verbose_name='BMC配制表外键'),
        ),
        migrations.AddField(
            model_name='bmccheckoutconf',
            name='nodeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.NodeInfo', verbose_name='节点表外键'),
        ),
    ]
