# Generated by Django 2.1.8 on 2020-03-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200323_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='nodeIpBmc',
            field=models.CharField(default='1', max_length=128, verbose_name='BMC IP地址'),
            preserve_default=False,
        ),
    ]
